version: '3.8'
name: dotnet-webapi-starter-kit
services:

  webapi:
    image: iammukeshm/dotnet-webapi-starter-kit:latest
    container_name: webapi
    pull_policy: always
    networks:
      - fullstackhero
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:16.1-alpine
    networks:
      - fullstackhero
    environment:
      - POSTGRES_USER=posgresqladmin
      - POSTGRES_PASSWORD=posgresqladmin
      - PGPORT=5433
    ports:
      - 5433:5433
    volumes:
      - postgres-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U posgresqladmin"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:   
    container_name: keycloak  
    image: quay.io/keycloak/keycloak:latest
    entrypoint: /opt/keycloak/bin/kc.sh start-dev --hostname-strict=false --hostname-port=7011
    networks:
      - fullstackhero
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: posgresqladmin
      DB_SCHEMA: public
      DB_PASSWORD: posgresqladmin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 7011:8080
    depends_on:
      - postgres

volumes:
  postgres-data:

networks:
  fullstackhero:
    name:  fullstackhero